### PR TITLE
issue 29: replace hardcoded "namespace: ahoy" 

### PR DESCRIPTION
**Pull request by mciverza**
…space }}" for better portability

may still need values section "rbacConfig"  policy.csv updated

https://github.com/lsdopen/charts/issues/29

### CODE REVIEW

**Comment by clivebor** [comment]
hey @mciverza,

Thanks for the PR!

I don't think you can use `{{ .Release.Namespace }}` in the values files.. I think the install will fail.

Another way of doing it would be to remove the namespace from metadata in all the templates, by default it will go to the release namespace. Still need it in the `cluster-role-binding > subjects` though.

Also, need to make sure to set the datasource url in `properties-prod-configmap` to something like:
`spring.datasource.url=jdbc:postgresql://ahoy-postgresql.{{ .Release.Namespace }}.svc/{{ .Values.postgresql.postgresqlDatabase }}`

The `ahoy` in rbacConfig refers to the ahoy account in the `config >  accounts.ahoy`, so its not making reference to the namespace.

**Comment by clivebor** [comment]
@mciverza the `sealedSecrets.controllerNamespace` is bit more tricky, we don't want to just make it the release namespace, because they may already have an install of sealed secrets that they'd want to re-use, this is why we allow them to change where it is in the values file.

I think in this case a template helper that defaults to `.Release.Namespace`, or the configured value if it is set is the way to go..

**Comment by mciverza** [comment]
> I don't think you can use {{ .Release.Namespace }} in the values files.

Seems to work.  I tested the installation as from my fork of the repo

**Comment by clivebor** [comment]
> 

Weird... I get this error when trying it:
`Error: failed to parse values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Release.Namespace":interface {}(nil)}`

It passes if you quote it, but then it treats it as a literal: 
`ahoy.sealed-secrets.controller-namespace={{ .Release.Namespace }}`

**Comment by clivebor** [comment]
@mciverza we made the relevant changes..

Please note; all references to the release name and namespace in the values file would need to be changed if different names are used.

**Pull request closed without merging**
